import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ModalProvider } from '@/context/modalContext'
import Box from '@mui/material/Box'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ModalProvider>
        <body>
          <Box
            sx={{
              width: 300,
              height: 300,
              flexDirection: 'column',
              display: 'flex',
              gap: '10px',
              padding: '10px',
            }}
          >
            {children}
          </Box>
        </body>
      </ModalProvider>
    </html>
  )
}
